#server setting
server:
  port: 8090
##########################################################
#view files
spring:
  mvc:
    view:
      prefix: templates
  aop:
    auto: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
##########################################################
#mybatis
mybatis:
  mapperLocation: classpath:/com/croplanet/memb/dao/*.xml
  mapperScanPackage: com.croplanet.memb.dao
  configLocation: classpath:/mybatis-runtime.xml
##########################################################
#data sources
#mysql
mysql:
  dataSourceType: com.alibaba.druid.pool.DruidDataSource
  #db1
  db1:
    datasource:
      url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      minIdle: 1
      maxActive: 10
      initialSize: 1
      maxWait: 60000
  #db2
  db1:
    datasource:
      url: jdbc:mysql://localhost:3306/db2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      minIdle: 1
      maxActive: 10
      initialSize: 1
      maxWait: 60000

##########################################################
#data records numbers in each table
maxRecordsPerTable: 10
#base name used to generate the name of tables that have same structure
tableBaseName: user

